x-postgres:
  &postgres-common
  image: "ankane/pgvector:v0.5.1"
  user: postgres
  healthcheck:
    test: "exit 0"
    interval: 2s
    timeout: 12s
    retries: 3

services:
  postgres:
    <<: *postgres-common
    container_name: "omnivore-postgres"
    ports:
      - "55432:5432"  # Changed to match PG_PORT
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  migrate:
    build:
      context: ../../
      dockerfile: ./packages/db/Dockerfile
    container_name: "omnivore-migrate"
    command: '/bin/sh ./packages/db/setup.sh'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  api:
    build:
      context: ../../
      dockerfile: ./packages/api/Dockerfile
    container_name: "omnivore-api"
    ports:
      - "54000:8080"  # Changed to match SERVER_BASE_URL
    healthcheck:
      test: ["CMD-SHELL", "nc -z 0.0.0.0 8080 || exit 1"]
      interval: 15s
      timeout: 90s
      retries: 6
    env_file:
      - .env
    depends_on:
      migrate:
        condition: service_completed_successfully 

  queue-processor:
    build:
      context: ../../
      dockerfile: ./packages/api/queue-processor/Dockerfile
    container_name: "omnivore-queue-processor"
    env_file:
      - .env
    depends_on:
      api:
        condition: service_healthy

  web:
    build:
      context: ../../
      dockerfile: ./packages/web/Dockerfile-self
      args:
        - APP_ENV=prod
        - BASE_URL=http://localhost:50003
        - SERVER_BASE_URL=http://localhost:54000
        - HIGHLIGHTS_BASE_URL=http://localhost:40003
        - USE_NATIVE_PDF=true
    container_name: "omnivore-web"
    ports:
      - "40003:8080"  # Changed to match BASE_URL
    env_file:
      - .env
    depends_on:
      api:
        condition: service_healthy

  image-proxy:
    build:
      context: ../../imageproxy
      dockerfile: ./Dockerfile
    container_name: "omnivore-image-proxy"
    ports:
      - "57070:8080"  # Changed to match IMAGE_PROXY_URL
    env_file:
      - .env

  content-fetch:
    build:
      context: ../../
      dockerfile: ./packages/content-fetch/Dockerfile
    container_name: "omnivore-content-fetch"
    ports:
      - "58080:8080"  # Changed to match GATEWAY_URL
    environment:
      - USE_FIREFOX=true
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      api:
        condition: service_healthy

  redis:
    image: "redis:7.2.4"
    container_name: "omnivore-redis"
    expose:
      - 56379
    ports:
      - "56379:6379"  # Changed to match REDIS_URL
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    expose:
      - 59000
    ports:
      - "51010:9000"  # Changed to match LOCAL_MINIO_URL
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 1s
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=miniominio"
      - "AWS_S3_ENDPOINT_URL=http://minio:59000"
    command: server /data
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniominio
      - BUCKET_NAME=omnivore
      - ENDPOINT=http://minio:59000
      - AWS_S3_ENDPOINT_URL=http://minio:59000
    depends_on:
      - minio
    entrypoint: >
      /bin/bash -c "
      sleep 5;
      until (/usr/bin/mc config host add myminio http://minio:59000 minio miniominio) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/omnivore;
      /usr/bin/mc policy set public myminio/omnivore;
      exit 0;
      "

  mail-watch-server:
    build:
      context: ../../
      dockerfile: ./packages/local-mail-watcher/Dockerfile
    container_name: "omnivore-mail-watch-server"
    ports:
      - "4398:8080"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

volumes:
  pgdata:
  redis_data:
  minio_data: